### PR TITLE
Create vie.ini

### PR DESCRIPTION
**Pull request by NhanAZ**

### CODE REVIEW

**Comment by boymelancholy** [comment]
SignEdit v1.3.2 will release soon.
Please give me the lang file after released.
Thanks.

**Comment by NhanAZ** [comment]
No way

**Comment by boymelancholy** [comment]
New feature will be added.
So this language file will be updated.

**Comment by NhanAZ** [comment]
If I remember correctly, I can edit my pull request after the update is available.

**Comment by boymelancholy** [comment]
Updated just now. :D

**Comment by NhanAZ** [comment]
Can you reopen this pull request?

**Comment by NhanAZ** [comment]
I deleted my branch so can't edit pull request. I will reopen a new pull request, thank you!

**Pull request closed without merging**
